name: Rust
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  NIGHTLY: 'nightly-2023-03-24'

jobs:
  check_lints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check format
      run: cargo fmt -- --check --files-with-diff

    - name: Check clippy lints
      run: cargo clippy --all-targets --verbose

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build with default settings
      run: |
        cargo build -v
        cargo build --release -v

    - name: Build docs
      run: cargo doc --verbose

    - name: Run tests
      run: cargo test --verbose

  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Miri
      run: rustup +$NIGHTLY component add miri

    - name: Run tests under Miri
      run: cargo +$NIGHTLY miri test